apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches-deployment
spec:
  selector:
    matchLabels:
      app: matches
  replicas: 1
  template:
    metadata:
      labels:
        app: matches
    spec:
      containers:
        - name: matches
          image: giorgossklavounakos/devops:football-scores-1.0.0
          ports:
            - containerPort: 80